### ISSUE TITLE
docker build -t xos . is failing: createdb: could not connect to database...

### ISSUE THREAD

**Issue by slavlvin** [open-cloud/xos#100]
Full error message:
"Creating XOS database...
createdb: could not connect to database template1: FATAL:  the database system is starting up".

I have tried to introduce delay 3 min as suggested in issue
"docker build -t xos . is failing due to postgresql not started - workaround include" - does not help.
Tried it on Ubuntu 12.04 and 14.04 - same error.

Any ideas?

**Comment by sbconsulting** [comment]
I've added and checked in a delay step to the wait for postgres to come online before creating the database, and expect this will solve the problem. We haven't reproduced the issue ourselves though (it seems dependent on the local environment), so if you could try the fix and let us know if it resolved for your environment, that would be helpful.

**Comment by slavlvin** [comment]
thanks, sbconsulting.
It did not help. Build was "successful", but run failed with "django.db.utils.OperationalError: FATAL:  the database system is starting up" - container never created.
Please see build and run log below:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
vlvin@vlvin-desktop1:~/XOS/xos1$ sudo docker build -t xos .
sudo: /var/lib/sudo writable by non-owner (040777), should be mode 0700
[sudo] password for vlvin: 
Cannot locate Dockerfile: Dockerfile
vlvin@vlvin-desktop1:~/XOS/xos1$ cd xos
vlvin@vlvin-desktop1:~/XOS/xos1/xos$ sudo docker build -t xos .
sudo: /var/lib/sudo writable by non-owner (040777), should be mode 0700
[sudo] password for vlvin: 
Sending build context to Docker daemon 12.85 MB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:14.04.2
 ---> d2a0ecffe6fa
Step 1 : MAINTAINER Andy Bavier <acb@cs.princeton.edu>
 ---> Using cache
 ---> 379097b3e3a0
Step 2 : RUN ln -s -f /bin/true /usr/bin/chfn
 ---> Using cache
 ---> 882b56132da1
Step 3 : RUN apt-get update
 ---> Using cache
 ---> 9f57539a9e56
Step 4 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git
 ---> Using cache
 ---> 736b67827478
Step 5 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql
 ---> Using cache
 ---> 588b020f9f36
Step 6 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-psycopg2
 ---> Using cache
 ---> 3cb62667a313
Step 7 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y graphviz graphviz-dev
 ---> Using cache
 ---> 2d6e6eec2796
Step 8 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libxslt1.1 libxslt1-dev
 ---> Using cache
 ---> 620d48122ac1
Step 9 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-pip
 ---> Using cache
 ---> afcf53d77c0d
Step 10 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tar
 ---> Using cache
 ---> d7c450bbb82f
Step 11 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y gcc
 ---> Using cache
 ---> f1e7c5416c95
Step 12 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-httplib2
 ---> Using cache
 ---> 7c51ddf140bf
Step 13 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y geoip-database libgeoip1
 ---> Using cache
 ---> 37496be46839
Step 14 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget
 ---> Using cache
 ---> e039326772db
Step 15 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-dev
 ---> Using cache
 ---> 386051bf0db3
Step 16 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libyaml-dev
 ---> Using cache
 ---> 034e870b11b4
Step 17 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y pkg-config
 ---> Using cache
 ---> 93a25eb98d50
Step 18 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-pycurl
 ---> Using cache
 ---> fae565e5c6b9
Step 19 : RUN pip install django==1.7
 ---> Using cache
 ---> 328eddab31b7
Step 20 : RUN pip install djangorestframework==2.4.4
 ---> Using cache
 ---> aa7f967e93f6
Step 21 : RUN pip install markdown  # Markdown support for the browseable API.
 ---> Using cache
 ---> 81c13d8865d6
Step 22 : RUN pip install pyyaml    # YAML content-type support.
 ---> Using cache
 ---> 36d223c4f0ee
Step 23 : RUN pip install django-filter  # Filtering support
 ---> Using cache
 ---> d8a004f1dfe7
Step 24 : RUN pip install lxml  # XML manipulation library
 ---> Using cache
 ---> 319a271a3353
Step 25 : RUN pip install netaddr # IP Addr library
 ---> Using cache
 ---> 68c01f83f1f7
Step 26 : RUN pip install pytz
 ---> Using cache
 ---> 7f42aee408c3
Step 27 : RUN pip install django-timezones
 ---> Using cache
 ---> 545118c70f09
Step 28 : RUN pip install requests
 ---> Using cache
 ---> fc91e4d6f1d5
Step 29 : RUN pip install django-crispy-forms
 ---> Using cache
 ---> a102d6b203af
Step 30 : RUN pip install django-geoposition
 ---> Using cache
 ---> 89af82f38233
Step 31 : RUN pip install django-extensions
 ---> Using cache
 ---> 4de634804bfe
Step 32 : RUN pip install django-suit
 ---> Using cache
 ---> 514ac236afbc
Step 33 : RUN pip install django-bitfield
 ---> Using cache
 ---> 4ad7d242705c
Step 34 : RUN pip install django-ipware
 ---> Using cache
 ---> a02c1a1d3621
Step 35 : RUN pip install django-encrypted-fields
 ---> Using cache
 ---> d13407aaaca2
Step 36 : RUN pip install python-keyczar
 ---> Using cache
 ---> 08413a488db1
Step 37 : RUN pip install pygraphviz
 ---> Using cache
 ---> cf979368f229
Step 38 : RUN pip install dnslib
 ---> Using cache
 ---> 878063d047c9
Step 39 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-keystoneclient
 ---> Using cache
 ---> 2b2ee6f24de6
Step 40 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-novaclient
 ---> Using cache
 ---> 3f698b57cecf
Step 41 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-neutronclient
 ---> Using cache
 ---> d1ebd72d78d4
Step 42 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-glanceclient
 ---> Using cache
 ---> d0f2df24c634
Step 43 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-ceilometerclient
 ---> Using cache
 ---> 4f34834c9b03
Step 44 : RUN pip install django_rest_swagger
 ---> Using cache
 ---> 6f63367c171c
Step 45 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-setuptools
 ---> Using cache
 ---> 75ca957c7b04
Step 46 : RUN easy_install django_evolution
 ---> Using cache
 ---> 830fb04969ed
Step 47 : RUN easy_install python_gflags
 ---> Using cache
 ---> 694db6cb6e00
Step 48 : RUN easy_install --upgrade httplib2
 ---> Using cache
 ---> b66fd4482742
Step 49 : RUN easy_install google_api_python_client
 ---> Using cache
 ---> 7dd355f30a31
Step 50 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-crypto
 ---> Using cache
 ---> acb438f99971
Step 51 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-yaml
 ---> Using cache
 ---> ee557972bbac
Step 52 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-client
 ---> Using cache
 ---> ccfc01e067cf
Step 53 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-paramiko
 ---> Using cache
 ---> a1a8510937e4
Step 54 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-jinja2
 ---> Using cache
 ---> a7fd1e2a0e5c
Step 55 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-httplib2
 ---> Using cache
 ---> c9b03ab44388
Step 56 : RUN git clone -b release1.8.2 git://github.com/ansible/ansible.git /opt/ansible
 ---> Using cache
 ---> 169bddba4327
Step 57 : RUN git clone -b release1.8.2 git://github.com/ansible/ansible-modules-extras.git /opt/ansible/lib/ansible/modules/extras
 ---> Using cache
 ---> 89c2e38caa78
Step 58 : RUN git clone -b release1.8.2 git://github.com/ansible/ansible-modules-extras.git /opt/ansible/v2/ansible/modules/extras
 ---> Using cache
 ---> 78c62cce8c55
Step 59 : RUN git clone git://github.com/sb98052/ansible-modules-core.git /opt/ansible/lib/ansible/modules/core
 ---> Using cache
 ---> 30f84d248f54
Step 60 : RUN git clone git://github.com/sb98052/ansible-modules-core.git /opt/ansible/v2/ansible/modules/core
 ---> Using cache
 ---> 9b672a6ff2b1
Step 61 : ADD ansible-hosts /etc/ansible/hosts
 ---> c6f52e9eea4b
Removing intermediate container 941e0fbf2055
Step 62 : ADD http://code.jquery.com/jquery-1.9.1.min.js /usr/local/lib/python2.7/dist-packages/suit/static/suit/js/
Downloading 92.63 kB

 ---> e958081cb7ea
Removing intermediate container ee3d9f6730ea
Step 63 : RUN git clone git://git.planet-lab.org/fofum.git /tmp/fofum
 ---> Running in 113099f1d63b
Cloning into '/tmp/fofum'...
 ---> 014c4a91db9b
Removing intermediate container 113099f1d63b
Step 64 : RUN cd /tmp/fofum; python setup.py install
 ---> Running in 9691ab39b6c4
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying fofum.py -> build/lib.linux-x86_64-2.7
running install_lib
copying build/lib.linux-x86_64-2.7/fofum.py -> /usr/local/lib/python2.7/dist-packages
byte-compiling /usr/local/lib/python2.7/dist-packages/fofum.py to fofum.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/fofum-1.0.egg-info
 ---> e223b75f7db4
Removing intermediate container 9691ab39b6c4
Step 65 : RUN rm -rf /tmp/fofum
 ---> Running in 96530425bc95
 ---> 76121cbf1869
Removing intermediate container 96530425bc95
Step 66 : RUN mkdir -p /usr/local/share /bin
 ---> Running in de91f8444ffb
 ---> d56c5ddf0e42
Removing intermediate container de91f8444ffb
Step 67 : ADD http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-x86_64.tar.bz2 /usr/local/share/
Downloading  13.2 MB/13.2 MB
 ---> a4b2ced33045
Removing intermediate container 1fa7b760cbeb
Step 68 : RUN tar jxvf /usr/local/share/phantomjs-1.7.0-linux-x86_64.tar.bz2 -C /usr/local/share/
 ---> Running in cf2edf3c204b
phantomjs-1.7.0-linux-x86_64/
phantomjs-1.7.0-linux-x86_64/ChangeLog
phantomjs-1.7.0-linux-x86_64/third-party.txt
phantomjs-1.7.0-linux-x86_64/bin/
phantomjs-1.7.0-linux-x86_64/bin/phantomjs
phantomjs-1.7.0-linux-x86_64/examples/
phantomjs-1.7.0-linux-x86_64/examples/unrandomize.coffee
phantomjs-1.7.0-linux-x86_64/examples/run-qunit.js
phantomjs-1.7.0-linux-x86_64/examples/injectme.coffee
phantomjs-1.7.0-linux-x86_64/examples/simpleserver.coffee
phantomjs-1.7.0-linux-x86_64/examples/scandir.js
phantomjs-1.7.0-linux-x86_64/examples/fibo.coffee
phantomjs-1.7.0-linux-x86_64/examples/unrandomize.js
phantomjs-1.7.0-linux-x86_64/examples/hello.js
phantomjs-1.7.0-linux-x86_64/examples/sleepsort.js
phantomjs-1.7.0-linux-x86_64/examples/phantomwebintro.coffee
phantomjs-1.7.0-linux-x86_64/examples/ipgeocode.coffee
phantomjs-1.7.0-linux-x86_64/examples/countdown.js
phantomjs-1.7.0-linux-x86_64/examples/run-jasmine.coffee
phantomjs-1.7.0-linux-x86_64/examples/netlog.coffee
phantomjs-1.7.0-linux-x86_64/examples/loadspeed.coffee
phantomjs-1.7.0-linux-x86_64/examples/loadspeed.js
phantomjs-1.7.0-linux-x86_64/examples/fibo.js
phantomjs-1.7.0-linux-x86_64/examples/waitfor.coffee
phantomjs-1.7.0-linux-x86_64/examples/seasonfood.js
phantomjs-1.7.0-linux-x86_64/examples/scandir.coffee
phantomjs-1.7.0-linux-x86_64/examples/outputEncoding.js
phantomjs-1.7.0-linux-x86_64/examples/rasterize.coffee
phantomjs-1.7.0-linux-x86_64/examples/direction.coffee
phantomjs-1.7.0-linux-x86_64/examples/imagebin.coffee
phantomjs-1.7.0-linux-x86_64/examples/universe.js
phantomjs-1.7.0-linux-x86_64/examples/render_multi_url.coffee
phantomjs-1.7.0-linux-x86_64/examples/waitfor.js
phantomjs-1.7.0-linux-x86_64/examples/movies.js
phantomjs-1.7.0-linux-x86_64/examples/technews.coffee
phantomjs-1.7.0-linux-x86_64/examples/tweets.coffee
phantomjs-1.7.0-linux-x86_64/examples/walk_through_frames.coffee
phantomjs-1.7.0-linux-x86_64/examples/modernizr.js
phantomjs-1.7.0-linux-x86_64/examples/netsniff.coffee
phantomjs-1.7.0-linux-x86_64/examples/pizza.js
phantomjs-1.7.0-linux-x86_64/examples/colorwheel.js
phantomjs-1.7.0-linux-x86_64/examples/pizza.coffee
phantomjs-1.7.0-linux-x86_64/examples/follow.coffee
phantomjs-1.7.0-linux-x86_64/examples/features.js
phantomjs-1.7.0-linux-x86_64/examples/tweets.js
phantomjs-1.7.0-linux-x86_64/examples/version.coffee
phantomjs-1.7.0-linux-x86_64/examples/run-jasmine.js
phantomjs-1.7.0-linux-x86_64/examples/postserver.js
phantomjs-1.7.0-linux-x86_64/examples/useragent.js
phantomjs-1.7.0-linux-x86_64/examples/render_multi_url.js
phantomjs-1.7.0-linux-x86_64/examples/version.js
phantomjs-1.7.0-linux-x86_64/examples/hello.coffee
phantomjs-1.7.0-linux-x86_64/examples/printenv.js
phantomjs-1.7.0-linux-x86_64/examples/technews.js
phantomjs-1.7.0-linux-x86_64/examples/countdown.coffee
phantomjs-1.7.0-linux-x86_64/examples/walk_through_frames.js
phantomjs-1.7.0-linux-x86_64/examples/colorwheel.coffee
phantomjs-1.7.0-linux-x86_64/examples/outputEncoding.coffee
phantomjs-1.7.0-linux-x86_64/examples/sleepsort.coffee
phantomjs-1.7.0-linux-x86_64/examples/printheaderfooter.js
phantomjs-1.7.0-linux-x86_64/examples/phantomwebintro.js
phantomjs-1.7.0-linux-x86_64/examples/post.coffee
phantomjs-1.7.0-linux-x86_64/examples/arguments.js
phantomjs-1.7.0-linux-x86_64/examples/printmargins.js
phantomjs-1.7.0-linux-x86_64/examples/netsniff.js
phantomjs-1.7.0-linux-x86_64/examples/ipgeocode.js
phantomjs-1.7.0-linux-x86_64/examples/netlog.js
phantomjs-1.7.0-linux-x86_64/examples/seasonfood.coffee
phantomjs-1.7.0-linux-x86_64/examples/run-qunit.coffee
phantomjs-1.7.0-linux-x86_64/examples/imagebin.js
phantomjs-1.7.0-linux-x86_64/examples/rasterize.js
phantomjs-1.7.0-linux-x86_64/examples/simpleserver.js
phantomjs-1.7.0-linux-x86_64/examples/echoToFile.js
phantomjs-1.7.0-linux-x86_64/examples/useragent.coffee
phantomjs-1.7.0-linux-x86_64/examples/arguments.coffee
phantomjs-1.7.0-linux-x86_64/examples/server.js
phantomjs-1.7.0-linux-x86_64/examples/movies.coffee
phantomjs-1.7.0-linux-x86_64/examples/injectme.js
phantomjs-1.7.0-linux-x86_64/examples/post.js
phantomjs-1.7.0-linux-x86_64/examples/module.js
phantomjs-1.7.0-linux-x86_64/examples/direction.js
phantomjs-1.7.0-linux-x86_64/examples/follow.js
phantomjs-1.7.0-linux-x86_64/examples/serverkeepalive.js
phantomjs-1.7.0-linux-x86_64/examples/detectsniff.js
phantomjs-1.7.0-linux-x86_64/examples/detectsniff.coffee
phantomjs-1.7.0-linux-x86_64/examples/echoToFile.coffee
phantomjs-1.7.0-linux-x86_64/README.md
phantomjs-1.7.0-linux-x86_64/LICENSE.BSD
 ---> ca669d0dc207
Removing intermediate container cf2edf3c204b
Step 69 : RUN rm -f /usr/local/share/phantomjs-1.7.0-linux-x86_64.tar.bz2
 ---> Running in 7a711b8a4892
 ---> 3c6fbd030d8f
Removing intermediate container 7a711b8a4892
Step 70 : RUN ln -s /usr/local/share/phantomjs-1.7.0-linux-x86_64 /usr/local/share/phantomjs
 ---> Running in 2834d446f30b
 ---> bee0c16ae5b1
Removing intermediate container 2834d446f30b
Step 71 : RUN ln -s /usr/local/share/phantomjs/bin/phantomjs /bin/phantomjs
 ---> Running in e242c57370e2
 ---> d938ac0a0468
Removing intermediate container e242c57370e2
Step 72 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y supervisor
 ---> Running in ed20fe0f29fd
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  python-meld3
The following NEW packages will be installed:
  python-meld3 supervisor
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 353 kB of archives.
After this operation, 1692 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe python-meld3 amd64 0.6.10-1 [39.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/universe supervisor all 3.0b2-1 [314 kB]
Fetched 353 kB in 7s (50.0 kB/s)
Selecting previously unselected package python-meld3.
(Reading database ... 23513 files and directories currently installed.)
Preparing to unpack .../python-meld3_0.6.10-1_amd64.deb ...
Unpacking python-meld3 (0.6.10-1) ...
Selecting previously unselected package supervisor.
Preparing to unpack .../supervisor_3.0b2-1_all.deb ...
Unpacking supervisor (3.0b2-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up python-meld3 (0.6.10-1) ...
Setting up supervisor (3.0b2-1) ...
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for ureadahead (0.100.0-16) ...
 ---> d568afd510de
Removing intermediate container ed20fe0f29fd
Step 73 : ADD observer.conf /etc/supervisor/conf.d/
 ---> d4170a9638c6
Removing intermediate container 8cb5f6faf84b
Step 74 : ADD xos /opt/xos
 ---> cc147dc494ac
Removing intermediate container d8b34bbd05e6
Step 75 : RUN chmod +x /opt/xos/scripts/opencloud
 ---> Running in ad8c72b80635
 ---> f441188890b6
Removing intermediate container ad8c72b80635
Step 76 : RUN /opt/xos/scripts/opencloud genkeys
 ---> Running in c31c825ff0e4
Generating keys
WARNING: 1024-bit key size is less than recommended default keysize of 2048 bits for RSA_PRIV keys.
 ---> f7abbf69404c
Removing intermediate container c31c825ff0e4
Step 77 : RUN mkdir /etc/ssl/private-copy; mv /etc/ssl/private/* /etc/ssl/private-copy/; rm -r /etc/ssl/private; mv /etc/ssl/private-copy /etc/ssl/private; chmod -R 0700 /etc/ssl/private; chown -R postgres /etc/ssl/private
 ---> Running in a14d794686d8
 ---> 7aa7b51ad0cd
Removing intermediate container a14d794686d8
Step 78 : RUN service postgresql start; sudo -u postgres psql -c "alter user postgres with password 'password';"
 ---> Running in 2fbb7c123ac8
 * Starting PostgreSQL 9.3 database server
   ...done.
ALTER ROLE
 ---> 1c802d3da443
Removing intermediate container 2fbb7c123ac8
Step 79 : RUN /opt/xos/scripts/opencloud remigrate
 ---> Running in 08ba737cedf0
 * Starting PostgreSQL 9.3 database server
   ...done.
Migrations for 'core':
  0001_initial.py:
    - Create model User
    - Create model Account
    - Create model Charge
    - Create model Controller
    - Create model ControllerCredential
    - Create model ControllerDashboardView
    - Create model ControllerImages
    - Create model ControllerNetwork
    - Create model ControllerRole
    - Create model ControllerSite
    - Create model ControllerSitePrivilege
    - Create model ControllerSlice
    - Create model ControllerSlicePrivilege
    - Create model ControllerUser
    - Create model DashboardView
    - Create model Deployment
    - Create model DeploymentPrivilege
    - Create model DeploymentRole
    - Create model Flavor
    - Create model Image
    - Create model ImageDeployments
    - Create model Invoice
    - Create model Network
    - Create model NetworkParameter
    - Create model NetworkParameterType
    - Create model NetworkSlice
    - Create model NetworkSliver
    - Create model NetworkTemplate
    - Create model Node
    - Create model Payment
    - Create model Project
    - Create model Reservation
    - Create model ReservedResource
    - Create model Role
    - Create model Router
    - Create model Service
    - Create model ServiceAttribute
    - Create model ServiceClass
    - Create model ServicePrivilege
    - Create model ServiceResource
    - Create model ServiceRole
    - Create model Site
    - Create model SiteCredential
    - Create model SiteDeployment
    - Create model SitePrivilege
    - Create model SiteRole
    - Create model Slice
    - Create model SliceCredential
    - Create model SlicePrivilege
    - Create model SliceRole
    - Create model SliceTag
    - Create model Sliver
    - Create model Tag
    - Create model Tenant
    - Create model TenantRoot
    - Create model TenantRootPrivilege
    - Create model TenantRootRole
    - Create model UsableObject
    - Create model UserCredential
    - Create model UserDashboardView
    - Add field role to tenantrootprivilege
    - Add field tenant_root to tenantrootprivilege
    - Add field user to tenantrootprivilege
    - Alter unique_together for tenantrootprivilege (1 constraint(s))
    - Add field subscriber_root to tenant
    - Add field subscriber_service to tenant
    - Add field subscriber_tenant to tenant
    - Add field subscriber_user to tenant
    - Add field role to sliceprivilege
    - Add field slice to sliceprivilege
    - Add field user to sliceprivilege
    - Alter unique_together for sliceprivilege (1 constraint(s))
    - Add field role to siteprivilege
    - Add field site to siteprivilege
    - Add field user to siteprivilege
    - Alter unique_together for sitedeployment (1 constraint(s))
    - Add field deployments to site
    - Add field role to serviceprivilege
    - Add field service to serviceprivilege
    - Add field user to serviceprivilege
    - Alter unique_together for serviceprivilege (1 constraint(s))
    - Add field owner to router
    - Add field permittedNetworks to router
    - Add field resource to reservedresource
    - Add field sliver to reservedresource
    - Add field slice to reservation
    - Add field site to node
    - Add field site_deployment to node
    - Add field sliver to networksliver
    - Alter unique_together for networksliver (1 constraint(s))
    - Add field slice to networkslice
    - Alter unique_together for networkslice (1 constraint(s))
    - Add field parameter to networkparameter
    - Add field owner to network
    - Add field permitted_slices to network
    - Add field slices to network
    - Add field slivers to network
    - Add field template to network
    - Alter unique_together for imagedeployments (1 constraint(s))
    - Add field deployments to image
    - Add field role to deploymentprivilege
    - Add field user to deploymentprivilege
    - Alter unique_together for deploymentprivilege (1 constraint(s))
    - Add field deployments to dashboardview
    - Alter unique_together for controlleruser (1 constraint(s))
    - Add field slice_privilege to controllersliceprivilege
    - Alter unique_together for controllersliceprivilege (1 constraint(s))
    - Add field slice to controllerslice
    - Alter unique_together for controllerslice (1 constraint(s))
    - Add field site_privilege to controllersiteprivilege
    - Alter unique_together for controllersiteprivilege (1 constraint(s))
    - Add field site to controllersite
    - Alter unique_together for controllersite (1 constraint(s))
    - Add field network to controllernetwork
    - Alter unique_together for controllernetwork (1 constraint(s))
    - Add field image to controllerimages
    - Alter unique_together for controllerimages (1 constraint(s))
    - Add field dashboardView to controllerdashboardview
    - Add field deployment to controller
    - Add field invoice to charge
    - Add field object to charge
    - Add field slice to charge
    - Add field site to account
    - Add field dashboards to user
    - Add field site to user
    - Create proxy model CoarseTenant
    - Create proxy model Provider
    - Create proxy model Subscriber
Migrations for 'hpc':
  0001_initial.py:
    - Create model AccessMap
    - Create model CDNPrefix
    - Create model ContentProvider
    - Create model HpcHealthCheck
    - Create model HpcService
    - Create model OriginServer
    - Create model ServiceProvider
    - Create model SiteMap
    - Add field hpcService to hpchealthcheck
    - Add field serviceProvider to contentprovider
    - Add field users to contentprovider
    - Add field contentProvider to cdnprefix
    - Add field defaultOriginServer to cdnprefix
    - Add field contentProvider to accessmap
Migrations for 'requestrouter':
  0001_initial.py:
    - Create model RequestRouterService
    - Create model ServiceMap
Migrations for 'syndicate_storage':
  0001_initial.py:
    - Create model SliceSecret
    - Create model SyndicatePrincipal
    - Create model SyndicateService
    - Create model Volume
    - Create model VolumeAccessRight
    - Create model VolumeSlice
    - Add field slice_id to volume
Migrations for 'cord':
  0001_initial.py:
    - Create proxy model CordSubscriberRoot
    - Create proxy model VBNGService
    - Create proxy model VBNGTenant
    - Create proxy model VCPEService
    - Create proxy model VCPETenant
    - Create proxy model VOLTService
    - Create proxy model VOLTTenant
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
Creating XOS database...
Syncing XOS services...
Operations to perform:
  Synchronize unmigrated apps: rest_framework_swagger, rest_framework, django_extensions, geoposition, suit
  Apply all migrations: cord, core, sessions, admin, syndicate_storage, auth, contenttypes, hpc, requestrouter
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying core.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying cord.0001_initial... FAKED
  Applying hpc.0001_initial... OK
  Applying requestrouter.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying syndicate_storage.0001_initial... OK
Loading initial data from fixture...
Installed 21 object(s) from 1 fixture(s)
 ---> 098015b7c799
Removing intermediate container 08ba737cedf0
Step 80 : RUN git -C /opt/ansible pull
 ---> Running in 39f44d570567
From git://github.com/ansible/ansible
   ba7243c..11be1ff  devel      -> origin/devel
   5d1fb38..122c53b  stable-1.9 -> origin/stable-1.9
Fetching submodule lib/ansible/modules/core
Already up-to-date.
 ---> ea6f63557efe
Removing intermediate container 39f44d570567
Step 81 : RUN git -C /opt/ansible/lib/ansible/modules/core pull
 ---> Running in b546226a7d7c
Already up-to-date.
 ---> 6258d01a6cb6
Removing intermediate container b546226a7d7c
Step 82 : RUN git -C /opt/ansible/v2/ansible/modules/core pull
 ---> Running in 0f8fac55502d
Already up-to-date.
 ---> 6e65b55cb6e4
Removing intermediate container 0f8fac55502d
Step 83 : EXPOSE 8000
 ---> Running in c3ab5332d8b7
 ---> 7d966dd1f717
Removing intermediate container c3ab5332d8b7
Step 84 : ENV HOME /root
 ---> Running in 7cb1712aa19a
 ---> 8378401cf504
Removing intermediate container 7cb1712aa19a
Step 85 : WORKDIR /root
 ---> Running in c7cb18d3cbd0
 ---> b33e937b1cd2
Removing intermediate container c7cb18d3cbd0
Step 86 : CMD service postgresql start; service supervisor start; cd /opt/xos; PUBLIC_HOSTNAME=`./xos-config.py get server_hostname $HOSTNAME`; python manage.py runserver $PUBLIC_HOSTNAME:8000 --insecure
 ---> Running in 0f401272d8b8
 ---> 5739420bc48a
Removing intermediate container 0f401272d8b8
Successfully built 5739420bc48a

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
vlvin@vlvin-desktop1:~/XOS/xos1/xos$ sudo docker run -t -i -p 8000:8000 xos
sudo: /var/lib/sudo writable by non-owner (040777), should be mode 0700
[sudo] password for vlvin: 
 * Starting PostgreSQL 9.3 database server                               [ OK ] 
Starting supervisor: supervisord.
Performing system checks...

System check identified no issues (0 silenced).
Unhandled exception in thread started by <function wrapper at 0x7f4a3c3a1d70>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 222, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 159, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 179, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.get_table_list(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 167, in cursor
    cursor = utils.CursorWrapper(self._cursor(), self)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 134, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  the database system is starting up

**Comment by sbconsulting** [comment]
Resolved.
