### ISSUE TITLE
xosproject/xos image: Initial login screen is messed up

### ISSUE THREAD

**Issue by andybavier** [open-cloud/xos#125]
Steps to reproduce the problem:

* $ cd xos/containers
* $ docker-compose up
* Pull up XOS GUI

![screen shot 2015-12-23 at 1 57 56 pm](https://cloud.githubusercontent.com/assets/283666/11982896/3fa62596-a97d-11e5-98ef-0385d9782354.png)

**Comment by teone** [comment]
@tmack-pl looks like some css is missing, `max-width: 100%` on the `#logo` container should fix.
