### ISSUE TITLE
Clean up planetstack/plstackapi references

### ISSUE THREAD

**Issue by llpeterson** [open-cloud/xos#18]
Clean up all planetstack and plstackapi references in source code. General housecleaning for release.

**Comment by sbconsulting** [comment]
Done:
   * Install directory (/opt/planetstack -> /opt/xos)
   * RPM name (opencloud -> xos)
   * Config file (plstackapi_config -> xos_config)
   * REST API: /plstackapi/ -> /xos/
   * observer entry point (planetstack-backend.py -> xos-observer.py)

To-Do:
   * git top level directory (planetstack -> xos)
   * application name (planetstack -> xos)
   * wsgi static dir (/var/www/planetstack -> /var/www/xos)

**Comment by sbconsulting** [comment]
Done.
