### ISSUE TITLE
Port forwarding does not work

### ISSUE THREAD

**Issue by sbconsulting** [open-cloud/xos#55]
I rebuilt opencloud-neutron-plugin to work on top of the ML2 neutron plugin. Instructions are in git.planet-lab.org: [opencloud-plugin.git] / ml2_plugin / README. Tested this on Washington.

Needs to be deployed to other Vicci headnodes and/or automated in install cloud.

Note the Juno supports "extension plugins" for ML2, and will yield a much cleaner approach.

**Comment by andybavier** [comment]
I've added Scott's Neutron changes to the nova-cloud-controller Juju charm and deployed it on all the clusters.  Port forwarding should be working on all clusters now, and should come up automatically when we install a new cluster.
