### ISSUE TITLE
Sliver flavor ID is wrong

### ISSUE THREAD

**Issue by andybavier** [open-cloud/xos#69]
In the Ansible template for a sliver, the flavor_id is wrong.  This should be the flavor ID in Nova, but it is getting set to the ID of the flavor object in XOS.  

On portal these two sets of IDs coincide so it happens to work.  We shouldn't rely on this - it doesn't work if you bring up a new XOS (e.g., from the Docker image) or run XOS against an OpenStack installation that doesn't have the default flavors.

**Comment by gwsapan** [comment]
Ok, I tried a hand at this, but then realized that every controller has its own set of ids. So I'm going to try making this change in Ansible, so that we supply flavor names instead of ids.
