### ISSUE TITLE
Lazy creation of Neutron networks

### ISSUE THREAD

**Issue by andybavier** [open-cloud/xos#74]
When a slice is created, the Observer currently creates a Neutron network on every cluster.  Each network imposes some overhead on the Neutron gateway VM, as a number of processes need to be run for each network instance.  We've experienced the Neutron VM running out of memory as a result of too many networks.

We should consider lazy creation of networks on VM instantiation.

**Comment by gwsapan** [comment]
This one is not going into Axtell, to use it, please pull from master.
