### ISSUE TITLE
docker build -t xos . is failing due to postgresql not started - workaround include

### ISSUE THREAD

**Issue by cboling** [open-cloud/xos#96]
With current master branch, running docker build -t . will fail during the 'opencloud' createdb step for the 'xos' database.   I was able to add the following lines before the 'createdb' step where it determined that postgresql had not yet fully started:
```
function createdb {
    echo "checking on DB '$DBNAME'"
    sudo -u postgres psql -e $DBNAME -c '\q'
    sudo -u postgres createdb -e $DBNAME
}
```
This resulted in the following output
```
   checking on DB 'xos'
   docker psql: FATAL: the database system is starting up
```
As a result, the script it fails to do the create and the rest of the dockerfile/script fails to successfully create the container.

A hack to work around this was to add a restart with a short pause at the top:
```
function createdb {
    sudo /etc/init.d/postgresql restart
    echo "Pausing a bit before continuing to insure it is ready"
    sleep 15
    echo "checking on DB '$DBNAME'"
    sudo -u postgres psql -e $DBNAME -c '\q'
    sudo -u postgres createdb -e $DBNAME
}
```
This results in the check for the 'xos' database to report it does not exist (which is what we want) and then the 'createdb' succeeds and the container is successfully created.  Not sure how long the sleep should be, but since this a one-time setup I thought 15 seconds would not be too bad.   The *psl* command could of course be removed since the output that the database does not exist may be interpreted as an error by a user doing a build.

Hope this helps someone else trying to create the docker container the first time.

**Comment by sbconsulting** [comment]
Thanks Chip,

I haven't been able to reliably reproduce this, although I think I've seen it happen intermittently. I'd like to have the delay automatically adjust, so it only delays for as long as the Postgres is not running. I was wondering if you could try the following in place for the "sleep 15" and let me know if it resolves the issue:

...
# wait for postgres to start
sudo -u postgres psql -c '\q' 
while [[ "$?" != "0" ]]; do 
    echo Waiting for postgres to start
    sleep 1
    sudo -u postgres psql -c '\q'
done 
...

Thanks, 
Scott

**Comment by cboling** [comment]
Scott,
 
I was able to test you suggestion and I was able to do the docker build on
my system.  It did take about 15 tries to finally pass (see output below) so
my original restart with a 15 second wait just happened to be lucky.   The
build was on an older 2-core Ubuntu 15.05 server running Docker version
1.5.0; build a8a31ef if that is of any help.
 
If there are any other things you wish me to try, feel free to send them my
way.   Thanks for the help on this.
 
   - Chip Boling
     Adtran

...
 
Migrations for 'syndicate_storage':
  0001_initial.py:
    - Create model SliceSecret
    - Create model SyndicatePrincipal
    - Create model SyndicateService
    - Create model Volume
    - Create model VolumeAccessRight
    - Create model VolumeSlice
    - Add field slice_id to volume
Inside remigrate function: cord setup
Migrations for 'cord':
  0001_initial.py:
    - Create proxy model VBNGService
    - Create proxy model VBNGTenant
    - Create proxy model VCPEService
    - Create proxy model VCPETenant
    - Create proxy model VOLTService
    - Create proxy model VOLTTenant
Inside remigrate function: exiting
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
psql: FATAL:  the database system is starting up
Waiting for postgres to start
Creating XOS database: 'xos'...
CREATE DATABASE xos;
Syncing XOS services...
Operations to perform:
  Synchronize unmigrated apps: rest_framework_swagger, rest_framework,
django_extensions, geoposition, suit
  Apply all migrations: cord, core, sessions, admin, syndicate_storage,
auth, contenttypes, hpc, requestrouter
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...



...



And finally sucess....


 

  _____

**Comment by sbconsulting** [comment]
Resolved.
